[package]
name = "adh"
version = "1.0.0"
authors = ["Joaquin Caro <jcaromiq@gmail.com>"]
edition = "2018"

[dependencies]
#shiplift =  "0.6.0"
shiplift = { git = "https://github.com/softprops/shiplift" }
tokio = { version = "0.2.22", features = ["macros"] }
async-trait = "0.1.38"
prettytable-rs = "0.8.0"
clap = "2.33.3"
futures = "0.3.5"
rand="0.7.3"
openssl = { version = "0.10.30", features = ["vendored"] }

#hyper-openssl = "0.8"


[dev-dependencies]
mockiato = "0.9.5"
pretty_assertions = "0.6.1"
predicates = "1.0.5"
assert_cmd = "1.0.1"

[profile.release]
opt-level = 'z'
lto = true
codegen-unit = 1
panic = 'abort'
