[package]
name = "adh"
version = "0.1.2"
authors = ["Joaquin Caro <jcaromiq@gmail.com>"]
edition = "2018"

[dependencies]
shiplift =  "0.6.0"
tokio = "0.1.21"
prettytable-rs = "0.8.0"
clap = "2.33.0"
futures = "0.1.27"
tokio-buf = "0.1.1"

[dev-dependencies]
mockiato = "0.9.5"
pretty_assertions = "0.6.1"
predicates = "1.0.3"
assert_cmd = "0.12.0"
