name: CI

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v1
      with:
        name: release-linux
        path: target/release/adh

  build-mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v1
      with:
        name: release-macOS
        path: target/release/adh
