name: Release

on:
  push:
    tags:        
      - v.*

jobs:
  release-mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        TAG_NAME=${GITHUB_REF##*/}
        VERSION=${TAG_NAME/v./}
        make upload version=${VERSION} hub_exec=bin/hub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

