name: Rust

on: [push]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test
    - name: Build
      run: cargo build --release

  build-mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test
    - name: Release
      run: cargo build --release

